### PR TITLE
Add MediaStreamTrack for adapter.js Firefox compatibility

### PR DESCRIPTION
**Pull request by a-type**
See: https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack

### CODE REVIEW

**Comment by jagoda** [comment]
How did the 1.0 commit get in here?

**Comment by jagoda** [comment]
I'm cool with merging this if we can clean out the rogue 1.0 commit. We should publish this under a minor version bump.

**Comment by a-type** [comment]
The 1.0 does not show up in my local repo. I'm not sure how to get rid of it.

**Comment by jagoda** [comment]
Strange. I have confirmed locally. It also seems to merge correctly locally. Good enough for me.

**Pull request merged**
